apiVersion: v1
kind: Service
metadata: 
  name: svc-swapidjango
  namespace: apiexemplo
spec:
  type: ClusterIP
  selector:
      app: swapidjango
  ports:
    - port: 5000
      name: http-5000
      protocol: TCP
      targetPort: 5000

